In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

Matplotlib is building the font cache; this may take a moment.

In [2]:
df = pd.read_csv('../../data/Gold_Market_10y.csv')
df.head()
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 2511 entries, 0 to 2510
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           2511 non-null   str
 1   Close          2511 non-null   float64
 2   High           2511 non-null   float64
 3   Low            2511 non-null   float64
 4   Open           2511 non-null   float64
 5   Volume         2511 non-null   int64
 6   Adj Close      2511 non-null   float64
 7   Daily_Return   2510 non-null   float64
 8   MA_20          2492 non-null   float64
 9   MA_50          2462 non-null   float64
 10  MA_200         2312 non-null   float64
 11  Volatility_20  2491 non-null   float64
 12  Year           2511 non-null   int64
 13  Month          2511 non-null   int64
 14  Day_of_Week    2511 non-null   int64
 15  Quarter        2511 non-null   int64
dtypes: float64(10), int64(5), str(1)
memory usage: 314.0 KB

,Close,High,Low,Open,Volume,Adj Close,Daily_Return,MA_20,MA_50,MA_200,Volatility_20,Year,Month,Day_of_Week,Quarter
count,2511.000000,2511.000000,2511.000000,2511.000000,2.511000e+03,2511.000000,2510.000000,2492.000000,2462.000000,2312.000000,2491.000000,2511.000000,2511.000000,2511.000000,2511.000000
mean,173.210382,173.940116,172.395440,173.200159,9.006663e+06,173.210382,0.062360,172.471327,171.414909,167.218717,0.871612,2020.561131,6.551971,2.026284,2.516527
std,63.167433,63.496196,62.677747,63.129388,5.063950e+06,63.167433,0.937345,61.198300,58.610260,48.713053,0.333071,2.878438,3.423202,1.400095,1.114387
min,106.949997,107.000000,106.260002,106.610001,1.436500e+06,106.949997,-6.426889,109.456000,112.089000,117.232300,0.287247,2016.000000,1.000000,0.000000,1.000000
25%,123.645000,123.990002,123.200001,123.704998,5.779900e+06,123.645000,-0.445586,123.500126,123.410400,122.558300,0.645702,2018.000000,4.000000,1.000000,2.000000
50%,164.929993,165.720001,164.289993,165.020004,7.757000e+06,164.929993,0.071563,164.909499,166.267700,167.865275,0.808752,2021.000000,7.000000,2.000000,3.000000
75%,183.399994,184.034996,182.260002,183.399994,1.069610e+07,183.399994,0.552166,182.536125,180.961800,178.757288,1.002644,2023.000000,10.000000,3.000000,4.000000
max,458.000000,458.750000,453.450012,454.109985,6.202500e+07,458.000000,4.903838,419.146002,400.148000,342.779000,2.487440,2026.000000,12.000000,4.000000,4.000000

In [3]:
df = df.dropna()

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2312 entries, 199 to 2510
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           2312 non-null   str
 1   Close          2312 non-null   float64
 2   High           2312 non-null   float64
 3   Low            2312 non-null   float64
 4   Open           2312 non-null   float64
 5   Volume         2312 non-null   int64
 6   Adj Close      2312 non-null   float64
 7   Daily_Return   2312 non-null   float64
 8   MA_20          2312 non-null   float64
 9   MA_50          2312 non-null   float64
 10  MA_200         2312 non-null   float64
 11  Volatility_20  2312 non-null   float64
 12  Year           2312 non-null   int64
 13  Month          2312 non-null   int64
 14  Day_of_Week    2312 non-null   int64
 15  Quarter        2312 non-null   int64
dtypes: float64(10), int64(5), str(1)
memory usage: 289.1 KB

In [8]:
x = df[['Open','High','Low','Volume','MA_20','MA_50','Volatility_20']]
y = df['Close']

In [7]:
df = df.reset_index(drop=True)
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 2312 entries, 0 to 2311
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           2312 non-null   str
 1   Close          2312 non-null   float64
 2   High           2312 non-null   float64
 3   Low            2312 non-null   float64
 4   Open           2312 non-null   float64
 5   Volume         2312 non-null   int64
 6   Adj Close      2312 non-null   float64
 7   Daily_Return   2312 non-null   float64
 8   MA_20          2312 non-null   float64
 9   MA_50          2312 non-null   float64
 10  MA_200         2312 non-null   float64
 11  Volatility_20  2312 non-null   float64
 12  Year           2312 non-null   int64
 13  Month          2312 non-null   int64
 14  Day_of_Week    2312 non-null   int64
 15  Quarter        2312 non-null   int64
dtypes: float64(10), int64(5), str(1)
memory usage: 289.1 KB

,Close,High,Low,Open,Volume,Adj Close,Daily_Return,MA_20,MA_50,MA_200,Volatility_20,Year,Month,Day_of_Week,Quarter
count,2312.000000,2312.000000,2312.000000,2312.000000,2.312000e+03,2312.000000,2312.000000,2312.000000,2312.000000,2312.000000,2312.000000,2312.000000,2312.000000,2312.000000,2312.000000
mean,177.620956,178.364157,176.784048,177.607881,8.800052e+06,177.620956,0.061696,176.364276,174.561103,167.218717,0.861789,2020.953720,6.584775,2.026384,2.527682
std,63.923495,64.264672,63.416587,63.884812,4.966632e+06,63.923495,0.927677,61.853746,59.117278,48.713053,0.335628,2.655795,3.476283,1.400283,1.124879
min,107.339996,107.989998,107.000000,107.470001,1.436500e+06,107.339996,-6.426889,109.456000,112.089000,117.232300,0.287247,2016.000000,1.000000,0.000000,1.000000
25%,125.537500,125.892502,125.159998,125.615002,5.669250e+06,125.537500,-0.440751,125.361125,124.259950,122.558300,0.633298,2019.000000,4.000000,1.000000,2.000000
50%,167.500000,168.004997,166.825005,167.419998,7.561000e+06,167.500000,0.073793,167.581248,167.626400,167.865275,0.795086,2021.000000,7.000000,2.000000,3.000000
75%,185.102505,186.040005,184.232502,185.012501,1.042748e+07,185.102505,0.552346,184.751000,182.322350,178.757288,0.985869,2023.000000,10.000000,3.000000,4.000000
max,458.000000,458.750000,453.450012,454.109985,6.202500e+07,458.000000,4.853035,419.146002,400.148000,342.779000,2.487440,2026.000000,12.000000,4.000000,4.000000

In [9]:
x_train, x_test, y_train, y_test = train_test_split(
    x,y, test_size=0.2, random_state=42
)

In [10]:
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [11]:
model = SVR(kernel='rbf')
model.fit(x_train, y_train)

SVR()

In [ ]:
y_pred = model.predict(x_test)
print("MSE: ", mean_squared_error(y_test, y_pred)) 
# Measures prediction error

print("R2: ", r2_score(y_test,y_pred))
# Model explains ~79% of variance in gold prices. 0.8+ → very good

MSE:  879.9726295421298
R2:  0.7923623045049251

In [14]:
SVR(C=100, gamma=0.1)

SVR(C=100, gamma=0.1)

In [15]:
model = SVR(kernel='rbf', C=100, gamma=0.1)
model.fit(x_train, y_train)

SVR(C=100, gamma=0.1)

In [16]:
y_pred = model.predict(x_test)

print("MSE: ", mean_squared_error(y_test, y_pred))
print("R2: ", r2_score(y_test, y_pred))

MSE:  12.379615190456471
R2:  0.9970789150901208

In [ ]:
# Getting R² ≈ 0.997 is almost too good This usually means:Data leakage or mistake in preprocessing